import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const DEMO_INFLUENCERS = [
  // Knitting niche
  {
    platform: "tiktok",
    username: "cozyknits_emma",
    displayName: "Emma | Cozy Knits",
    bio: "Knitting patterns & tutorials. Making cozy things since 2019. DM for collabs!",
    profileUrl: "https://tiktok.com/@cozyknits_emma",
    avatarUrl: null,
    followers: 4200,
    following: 312,
    engagement: 8.5,
    niche: "knitting",
    location: "Portland, OR",
    avgLikes: 356,
    avgComments: 45,
    avgViews: 12000,
  },
  {
    platform: "instagram",
    username: "yarn_therapy",
    displayName: "Sarah | Yarn Therapy",
    bio: "Knitting is my therapy. Sharing patterns, tips & yarn hauls.",
    profileUrl: "https://instagram.com/yarn_therapy",
    avatarUrl: null,
    followers: 3800,
    following: 420,
    engagement: 6.2,
    niche: "knitting",
    location: "Seattle, WA",
    avgLikes: 235,
    avgComments: 32,
    avgViews: null,
  },
  {
    platform: "youtube",
    username: "KnitWithMe",
    displayName: "Knit With Me",
    bio: "Beginner-friendly knitting tutorials. New video every Sunday!",
    profileUrl: "https://youtube.com/@KnitWithMe",
    avatarUrl: null,
    followers: 8900,
    following: null,
    engagement: 4.8,
    niche: "knitting",
    location: "Austin, TX",
    avgLikes: 427,
    avgComments: 89,
    avgViews: 15000,
  },
  // Fitness niche
  {
    platform: "tiktok",
    username: "homegym_gains",
    displayName: "Jake | Home Gym Gains",
    bio: "Building muscle at home. No gym needed! Workout tips & motivation.",
    profileUrl: "https://tiktok.com/@homegym_gains",
    avatarUrl: null,
    followers: 12500,
    following: 156,
    engagement: 7.2,
    niche: "fitness",
    location: "Denver, CO",
    avgLikes: 900,
    avgComments: 78,
    avgViews: 25000,
  },
  {
    platform: "instagram",
    username: "yoga_with_rachel",
    displayName: "Rachel | Yoga Flow",
    bio: "Yoga instructor & wellness advocate. Daily flows for busy people.",
    profileUrl: "https://instagram.com/yoga_with_rachel",
    avatarUrl: null,
    followers: 18000,
    following: 890,
    engagement: 5.5,
    niche: "fitness",
    location: "Los Angeles, CA",
    avgLikes: 990,
    avgComments: 120,
    avgViews: null,
  },
  // Food & Cooking niche
  {
    platform: "tiktok",
    username: "quickmeals_mike",
    displayName: "Mike | 15 Min Meals",
    bio: "Quick & easy recipes for busy people. Cook more, stress less!",
    profileUrl: "https://tiktok.com/@quickmeals_mike",
    avatarUrl: null,
    followers: 7800,
    following: 234,
    engagement: 9.1,
    niche: "food",
    location: "Chicago, IL",
    avgLikes: 710,
    avgComments: 95,
    avgViews: 18000,
  },
  {
    platform: "instagram",
    username: "plantbased_paula",
    displayName: "Paula | Plant Based Eats",
    bio: "Vegan recipes that actually taste good. Recipe developer & food stylist.",
    profileUrl: "https://instagram.com/plantbased_paula",
    avatarUrl: null,
    followers: 9500,
    following: 567,
    engagement: 6.8,
    niche: "food",
    location: "San Francisco, CA",
    avgLikes: 646,
    avgComments: 82,
    avgViews: null,
  },
  // Fashion niche
  {
    platform: "tiktok",
    username: "thriftflip_tina",
    displayName: "Tina | Thrift Flips",
    bio: "Transforming thrift finds into trendy fits. Sustainable fashion advocate.",
    profileUrl: "https://tiktok.com/@thriftflip_tina",
    avatarUrl: null,
    followers: 15200,
    following: 445,
    engagement: 8.9,
    niche: "fashion",
    location: "Brooklyn, NY",
    avgLikes: 1352,
    avgComments: 167,
    avgViews: 32000,
  },
  {
    platform: "instagram",
    username: "menswear_marcus",
    displayName: "Marcus | Modern Menswear",
    bio: "Affordable style tips for modern men. Fashion doesn't have to break the bank.",
    profileUrl: "https://instagram.com/menswear_marcus",
    avatarUrl: null,
    followers: 11000,
    following: 380,
    engagement: 5.2,
    niche: "fashion",
    location: "Atlanta, GA",
    avgLikes: 572,
    avgComments: 65,
    avgViews: null,
  },
  // Tech niche
  {
    platform: "youtube",
    username: "BudgetTechReviews",
    displayName: "Budget Tech Reviews",
    bio: "Honest reviews of affordable tech. Finding value in every price range.",
    profileUrl: "https://youtube.com/@BudgetTechReviews",
    avatarUrl: null,
    followers: 22000,
    following: null,
    engagement: 4.2,
    niche: "tech",
    location: "Miami, FL",
    avgLikes: 924,
    avgComments: 156,
    avgViews: 45000,
  },
  {
    platform: "tiktok",
    username: "appreviews_alex",
    displayName: "Alex | App Reviews",
    bio: "Reviewing the best apps so you don't have to. iOS & Android tips.",
    profileUrl: "https://tiktok.com/@appreviews_alex",
    avatarUrl: null,
    followers: 8400,
    following: 189,
    engagement: 7.6,
    niche: "tech",
    location: "Boston, MA",
    avgLikes: 638,
    avgComments: 72,
    avgViews: 16000,
  },
  // Pets niche
  {
    platform: "instagram",
    username: "doggydaily_diana",
    displayName: "Diana & Cooper",
    bio: "Life with a golden retriever. Tips, training & too many cute pics.",
    profileUrl: "https://instagram.com/doggydaily_diana",
    avatarUrl: null,
    followers: 14500,
    following: 678,
    engagement: 9.8,
    niche: "pets",
    location: "Nashville, TN",
    avgLikes: 1421,
    avgComments: 245,
    avgViews: null,
  },
  {
    platform: "tiktok",
    username: "catlife_chloe",
    displayName: "Chloe & Whiskers",
    bio: "Cat mom to 3 rescue babies. Daily cat content & adoption advocacy.",
    profileUrl: "https://tiktok.com/@catlife_chloe",
    avatarUrl: null,
    followers: 6700,
    following: 312,
    engagement: 11.2,
    niche: "pets",
    location: "Philadelphia, PA",
    avgLikes: 750,
    avgComments: 134,
    avgViews: 14000,
  },
  // DIY & Crafts niche
  {
    platform: "youtube",
    username: "DIYDanielle",
    displayName: "DIY with Danielle",
    bio: "Home decor DIYs on a budget. Making your space beautiful for less.",
    profileUrl: "https://youtube.com/@DIYDanielle",
    avatarUrl: null,
    followers: 19500,
    following: null,
    engagement: 5.6,
    niche: "diy",
    location: "Phoenix, AZ",
    avgLikes: 1092,
    avgComments: 178,
    avgViews: 38000,
  },
  {
    platform: "tiktok",
    username: "craftcorner_casey",
    displayName: "Casey | Craft Corner",
    bio: "Quick crafts & creative projects. Perfect for craft night inspiration!",
    profileUrl: "https://tiktok.com/@craftcorner_casey",
    avatarUrl: null,
    followers: 5200,
    following: 267,
    engagement: 8.3,
    niche: "diy",
    location: "Minneapolis, MN",
    avgLikes: 432,
    avgComments: 56,
    avgViews: 11000,
  },
  // Beauty niche
  {
    platform: "instagram",
    username: "glowup_grace",
    displayName: "Grace | Glow Up",
    bio: "Skincare tips for all skin types. Honest reviews & routines.",
    profileUrl: "https://instagram.com/glowup_grace",
    avatarUrl: null,
    followers: 16800,
    following: 512,
    engagement: 6.4,
    niche: "beauty",
    location: "San Diego, CA",
    avgLikes: 1075,
    avgComments: 143,
    avgViews: null,
  },
  {
    platform: "tiktok",
    username: "makeupbymia",
    displayName: "Mia | Makeup Magic",
    bio: "Drugstore makeup that looks expensive. Tutorials & product reviews.",
    profileUrl: "https://tiktok.com/@makeupbymia",
    avatarUrl: null,
    followers: 21000,
    following: 345,
    engagement: 7.8,
    niche: "beauty",
    location: "Houston, TX",
    avgLikes: 1638,
    avgComments: 198,
    avgViews: 42000,
  },
  // Travel niche
  {
    platform: "instagram",
    username: "budgettravel_ben",
    displayName: "Ben | Budget Traveler",
    bio: "Exploring the world without breaking the bank. Travel tips & guides.",
    profileUrl: "https://instagram.com/budgettravel_ben",
    avatarUrl: null,
    followers: 13200,
    following: 890,
    engagement: 5.8,
    niche: "travel",
    location: "Various",
    avgLikes: 766,
    avgComments: 98,
    avgViews: null,
  },
  {
    platform: "youtube",
    username: "VanLifeVicky",
    displayName: "Van Life with Vicky",
    bio: "Full-time van lifer sharing the adventure. Tips, builds & destinations.",
    profileUrl: "https://youtube.com/@VanLifeVicky",
    avatarUrl: null,
    followers: 28000,
    following: null,
    engagement: 4.5,
    niche: "travel",
    location: "On the road",
    avgLikes: 1260,
    avgComments: 210,
    avgViews: 52000,
  },
  // Parenting niche
  {
    platform: "instagram",
    username: "momlife_michelle",
    displayName: "Michelle | Real Mom Life",
    bio: "Mom of 3. Keeping it real about parenting. Tips, fails & wins.",
    profileUrl: "https://instagram.com/momlife_michelle",
    avatarUrl: null,
    followers: 9800,
    following: 645,
    engagement: 7.2,
    niche: "parenting",
    location: "Dallas, TX",
    avgLikes: 706,
    avgComments: 112,
    avgViews: null,
  },
  {
    platform: "tiktok",
    username: "daddydiaries_dan",
    displayName: "Dan | Daddy Diaries",
    bio: "Stay-at-home dad of twins. Parenting tips & dad humor.",
    profileUrl: "https://tiktok.com/@daddydiaries_dan",
    avatarUrl: null,
    followers: 7200,
    following: 278,
    engagement: 9.4,
    niche: "parenting",
    location: "Columbus, OH",
    avgLikes: 677,
    avgComments: 89,
    avgViews: 15500,
  },
  // Gaming niche
  {
    platform: "youtube",
    username: "IndieGameHunter",
    displayName: "Indie Game Hunter",
    bio: "Finding hidden gem indie games so you don't have to. Reviews & gameplay.",
    profileUrl: "https://youtube.com/@IndieGameHunter",
    avatarUrl: null,
    followers: 18500,
    following: null,
    engagement: 5.1,
    niche: "gaming",
    location: "Seattle, WA",
    avgLikes: 944,
    avgComments: 167,
    avgViews: 35000,
  },
  {
    platform: "tiktok",
    username: "cozygamer_kate",
    displayName: "Kate | Cozy Gamer",
    bio: "Cozy games & chill vibes. Stardew, Animal Crossing & more.",
    profileUrl: "https://tiktok.com/@cozygamer_kate",
    avatarUrl: null,
    followers: 11800,
    following: 423,
    engagement: 8.7,
    niche: "gaming",
    location: "Portland, OR",
    avgLikes: 1027,
    avgComments: 134,
    avgViews: 24000,
  },
  // Lifestyle niche
  {
    platform: "instagram",
    username: "minimalist_maya",
    displayName: "Maya | Minimal Living",
    bio: "Living more with less. Minimalism, organization & intentional living.",
    profileUrl: "https://instagram.com/minimalist_maya",
    avatarUrl: null,
    followers: 24500,
    following: 320,
    engagement: 5.9,
    niche: "lifestyle",
    location: "Denver, CO",
    avgLikes: 1446,
    avgComments: 178,
    avgViews: null,
  },
  {
    platform: "tiktok",
    username: "morningroutine_mel",
    displayName: "Mel | Morning Routines",
    bio: "Productive morning routines & self-care tips. Start your day right!",
    profileUrl: "https://tiktok.com/@morningroutine_mel",
    avatarUrl: null,
    followers: 15600,
    following: 356,
    engagement: 7.4,
    niche: "lifestyle",
    location: "Charlotte, NC",
    avgLikes: 1154,
    avgComments: 145,
    avgViews: 28000,
  },
];

async function main() {
  console.log("Seeding database...");

  for (const influencer of DEMO_INFLUENCERS) {
    await prisma.influencer.upsert({
      where: {
        platform_username: {
          platform: influencer.platform,
          username: influencer.username,
        },
      },
      update: influencer,
      create: influencer,
    });
  }

  console.log(`Seeded ${DEMO_INFLUENCERS.length} influencers`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
